/**
 * Generate dist/sw.js after vite build — hand-rolled service worker (ADR-002).
 * Precache-everything, cache-first, versioned by a content hash of the file
 * list. The app must fully function on first offline launch after one online
 * load (SPEC §3.1).
 */
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const dist = new URL('../dist', import.meta.url).pathname;

function walk(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) out.push(...walk(p));
    else out.push(p);
  }
  return out;
}

const files = walk(dist)
  .map((p) => '/' + relative(dist, p).replaceAll('\\', '/'))
  .filter((p) => p !== '/sw.js' && !p.endsWith('.map'));

const hash = createHash('sha256');
for (const f of files.sort()) {
  hash.update(f);
  hash.update(readFileSync(join(dist, f.slice(1))));
}
const version = hash.digest('hex').slice(0, 12);

const urls = files.map((f) => (f === '/index.html' ? '/' : f));
if (!urls.includes('/')) urls.push('/');

const sw = `/* SQUARE service worker — generated by scripts/build-sw.mjs. Precache-everything,
   cache-first, versioned. No runtime network use beyond same-origin precached assets. */
const CACHE = 'square-${version}';
const PRECACHE = ${JSON.stringify(urls, null, 1)};

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return; // never proxy cross-origin — there is none
  e.respondWith(
    caches.match(req.mode === 'navigate' ? '/' : req, { ignoreSearch: req.mode === 'navigate' }).then(
      (hit) => hit ?? fetch(req).then((res) => {
        if (res.ok) {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(req, copy));
        }
        return res;
      })
    )
  );
});
`;

writeFileSync(join(dist, 'sw.js'), sw);
const total = files.reduce((n, f) => n + statSync(join(dist, f.slice(1))).size, 0);
console.log(`sw.js written: ${files.length} precached files, version ${version}, ${(total / 1024).toFixed(0)} KB raw`);

// Emit _headers and _redirects into dist so drag-and-drop deploys carry the
// same headers netlify.toml gives repo-connected deploys. Permissions-Policy
// is what un-blocks the sensors — without it a Drop deploy ships a stud
// finder that cannot feel the wall (ADR-014).
const headersFile = `/*
  Permissions-Policy: accelerometer=(self), gyroscope=(self), magnetometer=(self), camera=(self), ambient-light-sensor=(self)
  Referrer-Policy: no-referrer
  X-Content-Type-Options: nosniff
  Cross-Origin-Opener-Policy: same-origin
  Content-Security-Policy: default-src 'self'; img-src 'self' blob: data:; media-src 'self' blob:; script-src 'self'; style-src 'self' 'unsafe-inline'; font-src 'self'; connect-src 'self'; worker-src 'self' blob:; base-uri 'none'; form-action 'none'; frame-ancestors 'none'

/sw.js
  Cache-Control: public, max-age=0, must-revalidate

/manifest.webmanifest
  Cache-Control: public, max-age=0, must-revalidate

/assets/*
  Cache-Control: public, max-age=31536000, immutable

/icons/*
  Cache-Control: public, max-age=31536000, immutable

/fonts/*
  Cache-Control: public, max-age=31536000, immutable
`;
writeFileSync(join(dist, '_headers'), headersFile);
writeFileSync(join(dist, '_redirects'), '/*  /index.html  200\n');
console.log('_headers and _redirects written for drag-and-drop deploys');
