/**
 * Precision/recall of the peak detector vs true SNR — SPEC §10.1:
 * "synthetic dipole signatures at known positions with injected noise at
 * multiple SNRs — verify precision/recall curves and that reported
 * confidence correlates monotonically with true SNR. Publish that curve."
 *
 * The printed markdown table IS the published curve: docs/accuracy-dsp.md
 * carries a copy, regenerated by running this file and copying the output.
 * Everything is seeded — the numbers are exact regressions.
 *
 * True SNR definition: lobe amplitude A over the post-filter noise floor
 * 0.505·σ_raw (the Savitzky-Golay window-9 white-noise gain), which is what
 * the detector's σ approximates on a blank stretch.
 */
import { describe, expect, it } from 'vitest';
import { analyzeMagTraceDetailed } from '../../src/dsp/analyze';
import { synthesizeTrace } from '../../src/dsp/synth';
import type { Confidence } from '../../src/types';

const SNR_LEVELS = [2, 3, 4, 5, 6, 8, 10, 12] as const;
const SEEDS_PER_LEVEL = 50;
const NOISE_RAW = 0.4; // µT per axis
const SG9_NOISE_GAIN = 0.505;
const TRUTH_IN = 10.0;
const TOL_IN = 0.75;

const CONF_RANK: Record<Confidence, number> = {
  UNRELIABLE: 0,
  NOISE: 0,
  POSSIBLE: 1,
  LIKELY: 2,
  STRONG: 3,
};

interface LevelStats {
  trueSnr: number;
  tp: number;
  fp: number;
  fn: number;
  recall: number;
  precision: number | null;
  /** Precision counting only detections the app would call LIKELY or better (SNR ≥ 5). */
  precisionLikely: number | null;
  meanMeasuredSnr: number | null;
  meanAbsErrIn: number | null;
  meanConfRank: number;
}

function runLevel(trueSnr: number): LevelStats {
  let tp = 0;
  let fp = 0;
  let fn = 0;
  let tpLikely = 0;
  let fpLikely = 0;
  let snrSum = 0;
  let errSum = 0;
  let confSum = 0;
  const amplitude = trueSnr * NOISE_RAW * SG9_NOISE_GAIN;
  for (let s = 0; s < SEEDS_PER_LEVEL; s++) {
    const trace = synthesizeTrace({
      id: `pr-${trueSnr}-${s}`,
      note: 'precision/recall sweep',
      seed: 100000 + trueSnr * 1000 + s,
      hz: 40,
      spanIn: 24,
      speedInPerS: 3.0,
      fasteners: [{ positionIn: TRUTH_IN, amplitude }],
      noise: NOISE_RAW,
      driftAmplitude: 0.5,
      expected: {
        peaks_in: [TRUTH_IN],
        tolerance_in: TOL_IN,
        pitch_in: null,
        confidence: 'NOISE',
        warnings: [],
      },
    });
    const res = analyzeMagTraceDetailed(trace);
    let hit = false;
    for (const ev of res.events) {
      const isHit = Math.abs(ev.positionIn - TRUTH_IN) <= TOL_IN && !hit;
      if (isHit) {
        hit = true;
        tp++;
        snrSum += ev.snr;
        errSum += Math.abs(ev.positionIn - TRUTH_IN);
        if (ev.snr >= 5) tpLikely++;
      } else {
        fp++; // off-position, or a duplicate claim on the same fastener
        if (ev.snr >= 5) fpLikely++;
      }
    }
    if (!hit) fn++;
    confSum += CONF_RANK[res.confidence];
  }
  return {
    trueSnr,
    tp,
    fp,
    fn,
    recall: tp / (tp + fn),
    precision: tp + fp > 0 ? tp / (tp + fp) : null,
    precisionLikely: tpLikely + fpLikely > 0 ? tpLikely / (tpLikely + fpLikely) : null,
    meanMeasuredSnr: tp > 0 ? snrSum / tp : null,
    meanAbsErrIn: tp > 0 ? errSum / tp : null,
    meanConfRank: confSum / SEEDS_PER_LEVEL,
  };
}

describe('precision/recall vs true SNR (SPEC §10.1)', () => {
  const stats = SNR_LEVELS.map(runLevel);

  it('publishes the curve (copy into docs/accuracy-dsp.md when it changes)', () => {
    const rows = stats.map((s) =>
      `| ${s.trueSnr} | ${s.recall.toFixed(2)} | ${s.precision === null ? '—' : s.precision.toFixed(2)} | ` +
      `${s.precisionLikely === null ? '—' : s.precisionLikely.toFixed(2)} | ` +
      `${s.meanMeasuredSnr === null ? '—' : s.meanMeasuredSnr.toFixed(1)} | ` +
      `${s.meanAbsErrIn === null ? '—' : s.meanAbsErrIn.toFixed(2)}″ | ${s.meanConfRank.toFixed(2)} |`,
    );
    console.log(
      [
        '| true SNR | recall | precision (all) | precision (LIKELY+) | mean detected SNR | mean |err| | mean confidence rank |',
        '|---|---|---|---|---|---|---|',
        ...rows,
      ].join('\n'),
    );
    expect(stats).toHaveLength(SNR_LEVELS.length);
  });

  it('recall is monotonically non-decreasing with true SNR', () => {
    for (let i = 1; i < stats.length; i++) {
      expect(
        stats[i]!.recall,
        `recall dropped from SNR ${stats[i - 1]!.trueSnr} (${stats[i - 1]!.recall}) to ${stats[i]!.trueSnr}`,
      ).toBeGreaterThanOrEqual(stats[i - 1]!.recall);
    }
  });

  it('recall saturates at ≥0.95 for SNR ≥ 6 and is meaningfully lower at SNR 2', () => {
    for (const s of stats) {
      if (s.trueSnr >= 6) expect(s.recall, `SNR ${s.trueSnr}`).toBeGreaterThanOrEqual(0.95);
    }
    // Bipolarity roughly doubles the evidence (prominence spans lobe to
    // saddle), so amplitude-SNR 2 still detects often — but must be clearly
    // below saturation.
    expect(stats[0]!.recall).toBeLessThan(0.9);
  });

  it('measured detection SNR correlates monotonically with true SNR', () => {
    const detected = stats.filter((s) => s.meanMeasuredSnr !== null);
    expect(detected.length).toBeGreaterThanOrEqual(5);
    for (let i = 1; i < detected.length; i++) {
      expect(
        detected[i]!.meanMeasuredSnr!,
        `mean detected SNR fell between true SNR ${detected[i - 1]!.trueSnr} and ${detected[i]!.trueSnr}`,
      ).toBeGreaterThan(detected[i - 1]!.meanMeasuredSnr!);
    }
  });

  it('reported confidence rank correlates monotonically with true SNR', () => {
    for (let i = 1; i < stats.length; i++) {
      expect(
        stats[i]!.meanConfRank,
        `confidence rank dropped between true SNR ${stats[i - 1]!.trueSnr} and ${stats[i]!.trueSnr}`,
      ).toBeGreaterThanOrEqual(stats[i - 1]!.meanConfRank);
    }
    // And the extremes are the right states, not merely ordered:
    expect(stats[0]!.meanConfRank).toBeLessThan(2.2); // SNR 2 sits below LIKELY on average
    expect(stats[stats.length - 1]!.meanConfRank).toBeGreaterThan(2.5); // SNR 12 ≈ STRONG
  });

  it('precision floor everywhere detections exist; high at strong SNR', () => {
    for (const s of stats) {
      if (s.precision !== null) {
        expect(s.precision, `precision at SNR ${s.trueSnr}`).toBeGreaterThanOrEqual(0.6);
      }
      if (s.trueSnr >= 10 && s.precision !== null) {
        expect(s.precision, `precision at SNR ${s.trueSnr}`).toBeGreaterThanOrEqual(0.85);
      }
    }
  });

  it('LIKELY-or-better claims are trustworthy: precision ≥ 0.9 from SNR 5 up', () => {
    for (const s of stats) {
      if (s.trueSnr >= 5 && s.precisionLikely !== null) {
        expect(s.precisionLikely, `LIKELY+ precision at SNR ${s.trueSnr}`).toBeGreaterThanOrEqual(0.9);
      }
    }
  });

  it('position error of true detections stays inside a quarter inch on average', () => {
    for (const s of stats) {
      if (s.trueSnr >= 5 && s.meanAbsErrIn !== null) {
        expect(s.meanAbsErrIn, `mean |err| at SNR ${s.trueSnr}`).toBeLessThanOrEqual(0.25);
      }
    }
  });
});
